version: "3.9"

services:
  bot:
    container_name: kua_bot
    build: ./
    networks:
      - kua
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
  db:
    container_name: kua_db
    image: mongo:latest
    networks:
      - kua
    privileged: true
    restart: always
    volumes:
      - ./dbdata:/data/db

networks:
  kua:
